# Codebase Reader Configuration

# Vector Database Settings
vector_db:
  type: "chromadb"
  persist_directory: "./chroma_db"
  collection_name: "codebase_chunks"
  distance_metric: "cosine"  # Recommended by OpenAI for their embeddings

# Embedding Settings
embeddings:
  default_provider: "sentence_transformers"  # Options: sentence_transformers, openai
  sentence_transformers:
    model_name: "all-MiniLM-L6-v2"
  openai:
    model: "text-embedding-ada-002"  # Latest and most cost-effective OpenAI model
    api_key_env: "OPENAI_API_KEY"
    dimensions: 1536  # text-embedding-ada-002 outputs 1536-dimensional vectors

# LLM Settings
llm:
  default_provider: "anthropic"  # Options: openai, anthropic
  openai:
    model: "gpt-3.5-turbo"
    api_key_env: "OPENAI_API_KEY"
    max_tokens: 1000
    temperature: 0.1
  anthropic:
    model: "claude-3-haiku-20240307"  # Options: claude-3-haiku-20240307, claude-3-sonnet-20240229, claude-3-opus-20240229
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 1000
    temperature: 0.1

# Chunking Settings
chunking:
  chunk_size: 1000
  chunk_overlap: 200
  max_file_size_mb: 10
  # Optimized for semantic coherence while staying within embedding limits

# Supported File Extensions
supported_extensions:
  - ".py"
  - ".js"
  - ".ts"
  - ".jsx"
  - ".tsx"
  - ".java"
  - ".cpp"
  - ".c"
  - ".h"
  - ".hpp"
  - ".cs"
  - ".go"
  - ".rs"
  - ".php"
  - ".rb"
  - ".swift"
  - ".kt"
  - ".scala"
  - ".sql"
  - ".html"
  - ".css"
  - ".md"
  - ".txt"
  - ".json"
  - ".yaml"
  - ".yml"

# Files/Directories to Ignore
ignore_patterns:
  # Version Control
  - ".git"
  - ".svn"
  - ".hg"
  
  # Node.js
  - "node_modules"
  - "npm-debug.log"
  - "yarn-debug.log"
  - "yarn-error.log"
  - ".pnpm-debug.log"
  
  # Python
  - "__pycache__"
  - ".pyc"
  - ".pyo"
  - ".pyd"
  - ".Python"
  - "pip-log.txt"
  - "pip-delete-this-directory.txt"
  - ".venv"
  - "venv"
  - "env"
  - ".env"
  - "ENV"
  - "env.bak"
  - "venv.bak"
  - ".pytest_cache"
  - ".coverage"
  - ".tox"
  
  # Build outputs
  - "dist"
  - "build"
  - "out"
  - "target"
  - "bin"
  - "obj"
  - "release"
  - "debug"
  
  # IDEs and Editors
  - ".vscode"
  - ".idea"
  - ".eclipse"
  - "*.swp"
  - "*.swo"
  - "*~"
  - ".DS_Store"
  - "Thumbs.db"
  
  # Web frameworks
  - ".next"
  - ".nuxt"
  - ".output"
  - ".cache"
  - ".parcel-cache"
  - ".webpack"
  
  # Databases
  - "*.db"
  - "*.sqlite"
  - "*.sqlite3"
  
  # Logs
  - "*.log"
  - "logs"
  - "*.log.*"
  
  # Dependencies (other languages)
  - "vendor"  # PHP, Go
  - "Pods"    # iOS CocoaPods
  - "packages"  # .NET
  - ".bundle"  # Ruby
  
  # Temporary and system files
  - "tmp"
  - "temp"
  - ".tmp"
  - ".temp"
  - "*.tmp"
  - "*.temp"
  
  # Large media files
  - "*.mp4"
  - "*.avi"
  - "*.mov"
  - "*.mp3"
  - "*.wav"
  - "*.flac"
  
  # Compressed files
  - "*.zip"
  - "*.tar.gz"
  - "*.rar"
  - "*.7z"
  
  # Documentation builds
  - "_site"
  - ".jekyll-cache"
  - "docs/_build"
  - "site"  # MkDocs default

# UI Settings
ui:
  page_title: "Codebase Reader & Analyzer"
  page_icon: "🔍"
  layout: "wide" 